### ISSUE TITLE
西安、大连、武汉，城市联盟MARK一下

### ISSUE THREAD

**Issue by quentinck** [madawei2699/xian-IT#12]

**Comment by quentinck** [comment]
西安、大连、武汉，城市联盟

**Comment by madawei2699** [comment]
什么意思？

**Comment by quentinck** [comment]
大连：github.com/yihong0618/dalian-IT
西安：https://github.com/madawei2699/xian-IT
武汉：https://github.com/smileArchitect/wuhan-IT
造福大家，加个星。
